// Major Arcana cards (22 cards)
const major = [
  "The Fool", "The Magician", "The High Priestess", "The Empress", "The Emperor",
  "The Hierophant", "The Lovers", "The Chariot", "Strength", "The Hermit",
  "Wheel of Fortune", "Justice", "The Hanged Man", "Death", "Temperance",
  "The Devil", "The Tower", "The Star", "The Moon", "The Sun", "Judgement", "The World"
];

// Minor Arcana suits and faces (56 cards)
const suits = ["Cups", "Pentacles", "Swords", "Wands"];
const faces = [
  "Ace", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight",
  "Nine", "Ten", "Page", "Knight", "Queen", "King"
];

// Combine suits and faces to build Minor Arcana
const minor = suits.flatMap(suit =>
  faces.map(face => `${face} of ${suit}`)
);

// Full Tarot deck (78 cards total)
export const fullDeck = [...major, ...minor];

// Simple shuffle function
export const shuffleDeck = () => [...fullDeck].sort(() => Math.random() - 0.5);

// Predefined card spreads with position names in English.
export const defaultSpreads = {
  3: ["Past", "Present", "Future"],
  5: ["Situation", "Challenge", "Advice", "External Influence", "Outcome"],
  7: ["You", "Obstacle", "Hidden Factor", "Advice", "Others", "Future", "Spiritual Insight"],
  10: [
    "Present", "Challenge", "Subconscious", "Past", "Conscious",
    "Near Future", "You", "Environment", "Hopes/Fears", "Outcome"
  ]
};

// Translations for tarot spread positions in multiple languages.
export const positions = {
  en: {
    "Past": "Past",
    "Present": "Present",
    "Future": "Future",
    "Situation": "Situation",
    "Challenge": "Challenge",
    "Advice": "Advice",
    "External Influence": "External Influence",
    "Outcome": "Outcome",
    "You": "You",
    "Obstacle": "Obstacle",
    "Hidden Factor": "Hidden Factor",
    "Others": "Others",
    "Spiritual Insight": "Spiritual Insight",
    "Subconscious": "Subconscious",
    "Conscious": "Conscious",
    "Near Future": "Near Future",
    "Environment": "Environment",
    "Hopes/Fears": "Hopes/Fears"
  },

  es: {
    "Past": "Pasado",
    "Present": "Presente",
    "Future": "Futuro",
    "Situation": "Situación",
    "Challenge": "Desafío",
    "Advice": "Consejo",
    "External Influence": "Influencia externa",
    "Outcome": "Resultado",
    "You": "Tú",
    "Obstacle": "Obstáculo",
    "Hidden Factor": "Factor oculto",
    "Others": "Otros",
    "Spiritual Insight": "Perspectiva espiritual",
    "Subconscious": "Subconsciente",
    "Conscious": "Consciente",
    "Near Future": "Futuro cercano",
    "Environment": "Entorno",
    "Hopes/Fears": "Esperanzas/Miedos"
  },

   de: {
    "Past": "Vergangenheit",
    "Present": "Gegenwart",
    "Future": "Zukunft",
    "Situation": "Situation",
    "Challenge": "Herausforderung",
    "Advice": "Rat",
    "External Influence": "Äußere Einflüsse",
    "Outcome": "Ergebnis",
    "You": "Du",
    "Obstacle": "Hindernis",
    "Hidden Factor": "Verborgener Faktor",
    "Others": "Andere",
    "Spiritual Insight": "Spirituelle Einsicht",
    "Subconscious": "Unterbewusstsein",
    "Conscious": "Bewusstsein",
    "Near Future": "Nahe Zukunft",
    "Environment": "Umfeld",
    "Hopes/Fears": "Hoffnungen/Ängste"
  },

  fr: {
    "Past": "Passé",
    "Present": "Présent",
    "Future": "Futur",
    "Situation": "Situation",
    "Challenge": "Défi",
    "Advice": "Conseil",
    "External Influence": "Influence extérieure",
    "Outcome": "Résultat",
    "You": "Vous",
    "Obstacle": "Obstacle",
    "Hidden Factor": "Facteur caché",
    "Others": "Autres",
    "Spiritual Insight": "Perspicacité spirituelle",
    "Subconscious": "Subconscient",
    "Conscious": "Conscient",
    "Near Future": "Proche avenir",
    "Environment": "Environnement",
    "Hopes/Fears": "Espoirs/Craintes"
  },

  pt: {
    "Past": "Passado",
    "Present": "Presente",
    "Future": "Futuro",
    "Situation": "Situação",
    "Challenge": "Desafio",
    "Advice": "Conselho",
    "External Influence": "Influência externa",
    "Outcome": "Resultado",
    "You": "Você",
    "Obstacle": "Obstáculo",
    "Hidden Factor": "Fator oculto",
    "Others": "Outros",
    "Spiritual Insight": "Visão espiritual",
    "Subconscious": "Subconsciente",
    "Conscious": "Consciente",
    "Near Future": "Futuro próximo",
    "Environment": "Ambiente",
    "Hopes/Fears": "Esperanças/Medos"
  },

  zh: {
    "Past": "过去",
    "Present": "现在",
    "Future": "未来",
    "Situation": "情境",
    "Challenge": "挑战",
    "Advice": "建议",
    "External Influence": "外部影响",
    "Outcome": "结果",
    "You": "你",
    "Obstacle": "障碍",
    "Hidden Factor": "隐藏因素",
    "Others": "他人",
    "Spiritual Insight": "精神启示",
    "Subconscious": "潜意识",
    "Conscious": "意识",
    "Near Future": "近期未来",
    "Environment": "环境",
    "Hopes/Fears": "希望/恐惧"
  },

  hi: {
    "Past": "अतीत",
    "Present": "वर्तमान",
    "Future": "भविष्य",
    "Situation": "परिस्थिति",
    "Challenge": "चुनौती",
    "Advice": "सलाह",
    "External Influence": "बाहरी प्रभाव",
    "Outcome": "परिणाम",
    "You": "आप",
    "Obstacle": "बाधा",
    "Hidden Factor": "छिपा हुआ कारक",
    "Others": "अन्य",
    "Spiritual Insight": "आध्यात्मिक अंतर्दृष्टि",
    "Subconscious": "अवचेतन",
    "Conscious": "चेतन",
    "Near Future": "निकट भविष्य",
    "Environment": "पर्यावरण",
    "Hopes/Fears": "आशाएं/डर"
  },

  ru: {
    "Past": "Прошлое",
    "Present": "Настоящее",
    "Future": "Будущее",
    "Situation": "Ситуация",
    "Challenge": "Проблема",
    "Advice": "Совет",
    "External Influence": "Внешнее влияние",
    "Outcome": "Результат",
    "You": "Ты",
    "Obstacle": "Препятствие",
    "Hidden Factor": "Скрытый фактор",
    "Others": "Другие",
    "Spiritual Insight": "Духовное понимание",
    "Subconscious": "Подсознание",
    "Conscious": "Сознание",
    "Near Future": "Ближайшее будущее",
    "Environment": "Окружение",
    "Hopes/Fears": "Надежды/Страхи"
  },

  hy: {
    "Past": "Անցյալ",
    "Present": "Ներկա",
    "Future": "Ապագա",
    "Situation": "Իրավիճակ",
    "Challenge": "Մարտահրավեր",
    "Advice": "Խորհուրդ",
    "External Influence": "Արտաքին ազդեցություն",
    "Outcome": "Արդյունք",
    "You": "Դու",
    "Obstacle": "Խոչընդոտ",
    "Hidden Factor": "Թաքնված գործոն",
    "Others": "Մյուսները",
    "Spiritual Insight": "Հոգևոր ընկալում",
    "Subconscious": "Ենթագիտակցություն",
    "Conscious": "Գիտակցություն",
    "Near Future": "Մոտ ապագա",
    "Environment": "Միջավայր",
    "Hopes/Fears": "Հույսեր/Վախեր"
  }
};



// Translations of the 22 Major Arcana tarot cards
// The key is the card name in English (as used in the original deck)

export const majorArcanaTranslations = {
  "The Fool": {
    en: "The Fool",
    pt: "O Louco",
    es: "El Loco",
    fr: "Le Fou",
    de: "Der Narr",
    ru: "Шут",
    hy: "Խենթը",
    hi: "मूर्ख",
    zh: "愚人",
  },
  "The Magician": {
    en: "The Magician",
    pt: "O Mago",
    es: "El Mago",
    fr: "Le Magicien",
    de: "Der Magier",
    ru: "Маг",
    hy: "Կախարդը",
    hi: "जादूगर",
    zh: "魔术师",
  },
  "The High Priestess": {
    en: "The High Priestess",
    pt: "A Sacerdotisa",
    es: "La Sacerdotisa",
    fr: "La Papesse",
    de: "Die Hohepriesterin",
    ru: "Жрица",
    hy: "Բարձր Քրմուհին",
    hi: "महायाजिका",
    zh: "女祭司",
  },
  "The Empress": {
    en: "The Empress",
    pt: "A Imperatriz",
    es: "La Emperatriz",
    fr: "L'Impératrice",
    de: "Die Herrscherin",
    ru: "Императрица",
    hy: "Կայսրուհին",
    hi: "सम्राज्ञी",
    zh: "女皇",
  },
  "The Emperor": {
    en: "The Emperor",
    pt: "O Imperador",
    es: "El Emperador",
    fr: "L'Empereur",
    de: "Der Herrscher",
    ru: "Император",
    hy: "Կայսրը",
    hi: "सम्राट",
    zh: "皇帝",
  },
  "The Hierophant": {
    en: "The Hierophant",
    pt: "O Hierofante",
    es: "El Sumo Sacerdote",
    fr: "Le Pape",
    de: "Der Hierophant",
    ru: "Иерофант",
    hy: "Քահանայապետը",
    hi: "महायाजक",
    zh: "教皇",
  },
  "The Lovers": {
    en: "The Lovers",
    pt: "Os Amantes",
    es: "Los Enamorados",
    fr: "Les Amoureux",
    de: "Die Liebenden",
    ru: "Влюбленные",
    hy: "Սիրահարները",
    hi: "प्रेमी",
    zh: "恋人",
  },
  "The Chariot": {
    en: "The Chariot",
    pt: "O Carro",
    es: "El Carro",
    fr: "Le Chariot",
    de: "Der Wagen",
    ru: "Колесница",
    hy: "Ռազմակառքը",
    hi: "रथ",
    zh: "战车",
  },
  "Strength": {
    en: "Strength",
    pt: "A Força",
    es: "La Fuerza",
    fr: "La Force",
    de: "Die Stärke",
    ru: "Сила",
    hy: "Ուժը",
    hi: "बल",
    zh: "力量",
  },
  "The Hermit": {
    en: "The Hermit",
    pt: "O Eremita",
    es: "El Ermitaño",
    fr: "L'Hermite",
    de: "Der Eremit",
    ru: "Отшельник",
    hy: "Մենավոր Պապը",
    hi: "संन्यासी",
    zh: "隐士",
  },
  "Wheel of Fortune": {
    en: "Wheel of Fortune",
    pt: "A Roda da Fortuna",
    es: "La Rueda de la Fortuna",
    fr: "La Roue de Fortune",
    de: "Das Rad des Schicksals",
    ru: "Колесо Фортуны",
    hy: "Բախտի Անիվը",
    hi: "भाग्य चक्र",
    zh: "命运之轮",
  },
  "Justice": {
    en: "Justice",
    pt: "A Justiça",
    es: "La Justicia",
    fr: "La Justice",
    de: "Die Gerechtigkeit",
    ru: "Справедливость",
    hy: "Արդարադատությունը",
    hi: "न्याय",
    zh: "正义",
  },
  "The Hanged Man": {
    en: "The Hanged Man",
    pt: "O Enforcado",
    es: "El Colgado",
    fr: "Le Pendu",
    de: "Der Gehängte",
    ru: "Повешенный",
    hy: "Կախվածը",
    hi: "फांसी पर लटका व्यक्ति",
    zh: "倒吊人",
  },
  "Death": {
    en: "Death",
    pt: "A Morte",
    es: "La Muerte",
    fr: "La Mort",
    de: "Der Tod",
    ru: "Смерть",
    hy: "Մահը",
    hi: "मृत्यु",
    zh: "死亡",
  },
  "Temperance": {
    en: "Temperance",
    pt: "A Temperança",
    es: "La Templanza",
    fr: "Tempérance",
    de: "Die Mäßigkeit",
    ru: "Умеренность",
    hy: "Միջոցառությունը",
    hi: "संयम",
    zh: "节制",
  },
  "The Devil": {
    en: "The Devil",
    pt: "O Diabo",
    es: "El Diablo",
    fr: "Le Diable",
    de: "Der Teufel",
    ru: "Дьявол",
    hy: "Սատանան",
    hi: "शैतान",
    zh: "恶魔",
  },
  "The Tower": {
    en: "The Tower",
    pt: "A Torre",
    es: "La Torre",
    fr: "La Tour",
    de: "Der Turm",
    ru: "Башня",
    hy: "Ապարանքը",
    hi: "मीनार",
    zh: "高塔",
  },
  "The Star": {
    en: "The Star",
    pt: "A Estrela",
    es: "La Estrella",
    fr: "L'Étoile",
    de: "Der Stern",
    ru: "Звезда",
    hy: "Աստղը",
    hi: "तारा",
    zh: "星星",
  },
  "The Moon": {
    en: "The Moon",
    pt: "A Lua",
    es: "La Luna",
    fr: "La Lune",
    de: "Der Mond",
    ru: "Луна",
    hy: "Լուսինը",
    hi: "चंद्रमा",
    zh: "月亮",
  },
  "The Sun": {
    en: "The Sun",
    pt: "O Sol",
    es: "El Sol",
    fr: "Le Soleil",
    de: "Die Sonne",
    ru: "Солнце",
    hy: "Արեւը",
    hi: "सूरज",
    zh: "太阳",
  },
  "Judgement": {
    en: "Judgement",
    pt: "O Julgamento",
    es: "El Juicio",
    fr: "Le Jugement",
    de: "Das Gericht",
    ru: "Суд",
    hy: "Դատաստանը",
    hi: "निर्णय",
    zh: "审判",
  },
  "The World": {
    en: "The World",
    pt: "O Mundo",
    es: "El Mundo",
    fr: "Le Monde",
    de: "Die Welt",
    ru: "Мир",
    hy: "Աշխարհը",
    hi: "दुनिया",
    zh: "世界",
  }
};

// Translations of the 56 Minor Arcana tarot cards
// The key is the card name in English

export const minorArcanaTranslations = {
  "Ace of Cups": {
    en: "Ace of Cups",
    es: "As de Copas",
    de: "Ass der Kelche",
    fr: "As de Coupes",
    pt: "Ás de Copas",
    zh: "圣杯王牌",
    hi: "कप का इक्का",
    ru: "Туз Кубков",
    hy: "Գավաթների Աս"
  },
  "Two of Cups": {
    en: "Two of Cups",
    es: "Dos de Copas",
    de: "Zwei der Kelche",
    fr: "Deux de Coupes",
    pt: "Dois de Copas",
    zh: "圣杯二",
    hi: "कप का दो",
    ru: "Двойка Кубков",
    hy: "Գավաթների Երկուս"
  },
  "Three of Cups": {
    en: "Three of Cups",
    es: "Tres de Copas",
    de: "Drei der Kelche",
    fr: "Trois de Coupes",
    pt: "Três de Copas",
    zh: "圣杯三",
    hi: "कप का तीन",
    ru: "Тройка Кубков",
    hy: "Գավաթների Երեք"
  },
  "Four of Cups": {
    en: "Four of Cups",
    es: "Cuatro de Copas",
    de: "Vier der Kelche",
    fr: "Quatre de Coupes",
    pt: "Quatro de Copas",
    zh: "圣杯四",
    hi: "कप का चार",
    ru: "Четвёрка Кубков",
    hy: "Գավաթների Չորս"
  },
  "Five of Cups": {
    en: "Five of Cups",
    es: "Cinco de Copas",
    de: "Fünf der Kelche",
    fr: "Cinq de Coupes",
    pt: "Cinco de Copas",
    zh: "圣杯五",
    hi: "कप का पाँच",
    ru: "Пятёрка Кубков",
    hy: "Գավաթների Հինգ"
  },
  "Six of Cups": {
    en: "Six of Cups",
    es: "Seis de Copas",
    de: "Sechs der Kelche",
    fr: "Six de Coupes",
    pt: "Seis de Copas",
    zh: "圣杯六",
    hi: "कप का छह",
    ru: "Шестёрка Кубков",
    hy: "Գավաթների Վեց"
  },
  "Seven of Cups": {
    en: "Seven of Cups",
    es: "Siete de Copas",
    de: "Sieben der Kelche",
    fr: "Sept de Coupes",
    pt: "Sete de Copas",
    zh: "圣杯七",
    hi: "कप का सात",
    ru: "Семёрка Кубков",
    hy: "Գավաթների Յոթ"
  },
  "Eight of Cups": {
    en: "Eight of Cups",
    es: "Ocho de Copas",
    de: "Acht der Kelche",
    fr: "Huit de Coupes",
    pt: "Oito de Copas",
    zh: "圣杯八",
    hi: "कप का आठ",
    ru: "Восьмёрка Кубков",
    hy: "Գավաթների Ութ"
  },
  "Nine of Cups": {
    en: "Nine of Cups",
    es: "Nueve de Copas",
    de: "Neun der Kelche",
    fr: "Neuf de Coupes",
    pt: "Nove de Copas",
    zh: "圣杯九",
    hi: "कप का नौ",
    ru: "Девятка Кубков",
    hy: "Գավաթների Ինը"
  },
  "Ten of Cups": {
    en: "Ten of Cups",
    es: "Diez de Copas",
    de: "Zehn der Kelche",
    fr: "Dix de Coupes",
    pt: "Dez de Copas",
    zh: "圣杯十",
    hi: "कप का दस",
    ru: "Десятка Кубков",
    hy: "Գավաթների Տասը"
  },
  "Page of Cups": {
    en: "Page of Cups",
    es: "Sota de Copas",
    de: "Bube der Kelche",
    fr: "Valet de Coupes",
    pt: "Valete de Copas",
    zh: "圣杯侍者",
    hi: "कप का पेज",
    ru: "Паж Кубков",
    hy: "Գավաթների Ծառա"
  },
  "Knight of Cups": {
    en: "Knight of Cups",
    es: "Caballo de Copas",
    de: "Ritter der Kelche",
    fr: "Cavalier de Coupes",
    pt: "Cavaleiro de Copas",
    zh: "圣杯骑士",
    hi: "कप का नाइट",
    ru: "Рыцарь Кубков",
    hy: "Գավաթների Ասպետ"
  },
  "Queen of Cups": {
    en: "Queen of Cups",
    es: "Reina de Copas",
    de: "Königin der Kelche",
    fr: "Reine de Coupes",
    pt: "Rainha de Copas",
    zh: "圣杯女王",
    hi: "कप की रानी",
    ru: "Королева Кубков",
    hy: "Գավաթների Թագուհի"
  },
  "King of Cups": {
    en: "King of Cups",
    es: "Rey de Copas",
    de: "König der Kelche",
    fr: "Roi de Coupes",
    pt: "Rei de Copas",
    zh: "圣杯国王",
    hi: "कप का राजा",
    ru: "Король Кубков",
    hy: "Գավաթների Թագավոր"
  },
  "Ace of Pentacles": {
    en: "Ace of Pentacles",
    es: "As de Oros",
    de: "Ass der Münzen",
    fr: "As de Deniers",
    pt: "Ás de Ouros",
    zh: "钱币王牌",
    hi: "सिक्कों का इक्का",
    ru: "Туз Пентаклей",
    hy: "Դրամների Էս"
  },
  "Two of Pentacles": {
    en: "Two of Pentacles",
    es: "Dos de Oros",
    de: "Zwei der Münzen",
    fr: "Deux de Deniers",
    pt: "Dois de Ouros",
    zh: "钱币二",
    hi: "सिक्कों का दो",
    ru: "Двойка Пентаклей",
    hy: "Դրամների Երկու"
  },
  "Three of Pentacles": {
    en: "Three of Pentacles",
    es: "Tres de Oros",
    de: "Drei der Münzen",
    fr: "Trois de Deniers",
    pt: "Três de Ouros",
    zh: "钱币三",
    hi: "सिक्कों का तीन",
    ru: "Тройка Пентаклей",
    hy: "Դրամների Երեք"
  },
  "Four of Pentacles": {
    en: "Four of Pentacles",
    es: "Cuatro de Oros",
    de: "Vier der Münzen",
    fr: "Quatre de Deniers",
    pt: "Quatro de Ouros",
    zh: "钱币四",
    hi: "सिक्कों का चार",
    ru: "Четвёрка Пентаклей",
    hy: "Դրամների Չորս"
  },
  "Five of Pentacles": {
    en: "Five of Pentacles",
    es: "Cinco de Oros",
    de: "Fünf der Münzen",
    fr: "Cinq de Deniers",
    pt: "Cinco de Ouros",
    zh: "钱币五",
    hi: "सिक्कों का पाँच",
    ru: "Пятёрка Пентаклей",
    hy: "Դրամների Հինգ"
  },
  "Six of Pentacles": {
    en: "Six of Pentacles",
    es: "Seis de Oros",
    de: "Sechs der Münzen",
    fr: "Six de Deniers",
    pt: "Seis de Ouros",
    zh: "钱币六",
    hi: "सिक्कों का छह",
    ru: "Шестёрка Пентаклей",
    hy: "Դրամների Վեց"
  },
  "Seven of Pentacles": {
    en: "Seven of Pentacles",
    es: "Siete de Oros",
    de: "Sieben der Münzen",
    fr: "Sept de Deniers",
    pt: "Sete de Ouros",
    zh: "钱币七",
    hi: "सिक्कों का सात",
    ru: "Семёрка Пентаклей",
    hy: "Դրամների Յոթ"
  },
  "Eight of Pentacles": {
    en: "Eight of Pentacles",
    es: "Ocho de Oros",
    de: "Acht der Münzen",
    fr: "Huit de Deniers",
    pt: "Oito de Ouros",
    zh: "钱币八",
    hi: "सिक्कों का आठ",
    ru: "Восьмёрка Пентаклей",
    hy: "Դրամների Ութ"
  },
  "Nine of Pentacles": {
    en: "Nine of Pentacles",
    es: "Nueve de Oros",
    de: "Neun der Münzen",
    fr: "Neuf de Deniers",
    pt: "Nove de Ouros",
    zh: "钱币九",
    hi: "सिक्कों का नौ",
    ru: "Девятка Пентаклей",
    hy: "Դրամների Իննը"
  },
  "Ten of Pentacles": {
    en: "Ten of Pentacles",
    es: "Diez de Oros",
    de: "Zehn der Münzen",
    fr: "Dix de Deniers",
    pt: "Dez de Ouros",
    zh: "钱币十",
    hi: "सिक्कों का दस",
    ru: "Десятка Пентаклей",
    hy: "Դրամների Տասը"
  },
  "Page of Pentacles": {
    en: "Page of Pentacles",
    es: "Sota de Oros",
    de: "Bube der Münzen",
    fr: "Valet de Deniers",
    pt: "Pajem de Ouros",
    zh: "钱币侍从",
    hi: "सिक्कों का पेज",
    ru: "Паж Пентаклей",
    hy: "Դրամների Նաժիշտ"
  },
  "Knight of Pentacles": {
    en: "Knight of Pentacles",
    es: "Caballero de Oros",
    de: "Ritter der Münzen",
    fr: "Cavalier de Deniers",
    pt: "Cavaleiro de Ouros",
    zh: "钱币骑士",
    hi: "सिक्कों का नाइट",
    ru: "Рыцарь Пентаклей",
    hy: "Դրամների Ասպետ"
  },
  "Queen of Pentacles": {
    en: "Queen of Pentacles",
    es: "Reina de Oros",
    de: "Königin der Münzen",
    fr: "Reine de Deniers",
    pt: "Rainha de Ouros",
    zh: "钱币皇后",
    hi: "सिक्कों की रानी",
    ru: "Королева Пентаклей",
    hy: "Դրամների Թագուհի"
  },
  "King of Pentacles": {
    en: "King of Pentacles",
    es: "Rey de Oros",
    de: "König der Münzen",
    fr: "Roi de Deniers",
    pt: "Rei de Ouros",
    zh: "钱币国王",
    hi: "सिक्कों का राजा",
    ru: "Король Пентаклей",
    hy: "Դրամների Թագավոր"
  },
  "Ace of Swords": {
    en: "Ace of Swords",
    es: "As de Espadas",
    de: "Ass der Schwerter",
    fr: "As d'Épées",
    pt: "Ás de Espadas",
    zh: "宝剑王牌",
    hi: "तलवारों का इक्का",
    ru: "Туз Мечей",
    hy: "Սրերի Էս"
  },
  "Two of Swords": {
    en: "Two of Swords",
    es: "Dos de Espadas",
    de: "Zwei der Schwerter",
    fr: "Deux d'Épées",
    pt: "Dois de Espadas",
    zh: "宝剑二",
    hi: "तलवारों का दो",
    ru: "Двойка Мечей",
    hy: "Սրերի Երկուս"
  },
  "Three of Swords": {
    en: "Three of Swords",
    es: "Tres de Espadas",
    de: "Drei der Schwerter",
    fr: "Trois d'Épées",
    pt: "Três de Espadas",
    zh: "宝剑三",
    hi: "तलवारों का तीन",
    ru: "Тройка Мечей",
    hy: "Սրերի Երեք"
  },
  "Four of Swords": {
    en: "Four of Swords",
    es: "Cuatro de Espadas",
    de: "Vier der Schwerter",
    fr: "Quatre d'Épées",
    pt: "Quatro de Espadas",
    zh: "宝剑四",
    hi: "तलवारों का चार",
    ru: "Четвёрка Мечей",
    hy: "Սրերի Չորս"
  },
  "Five of Swords": {
    en: "Five of Swords",
    es: "Cinco de Espadas",
    de: "Fünf der Schwerter",
    fr: "Cinq d'Épées",
    pt: "Cinco de Espadas",
    zh: "宝剑五",
    hi: "तलवारों का पाँच",
    ru: "Пятёрка Мечей",
    hy: "Սրերի Հինգ"
  },
  "Six of Swords": {
    en: "Six of Swords",
    es: "Seis de Espadas",
    de: "Sechs der Schwerter",
    fr: "Six d'Épées",
    pt: "Seis de Espadas",
    zh: "宝剑六",
    hi: "तलवारों का छह",
    ru: "Шестёрка Мечей",
    hy: "Սրերի Վեց"
  },
  "Seven of Swords": {
    en: "Seven of Swords",
    es: "Siete de Espadas",
    de: "Sieben der Schwerter",
    fr: "Sept d'Épées",
    pt: "Sete de Espadas",
    zh: "宝剑七",
    hi: "तलवारों का सात",
    ru: "Семёрка Мечей",
    hy: "Սրերի Յոթ"
  },
  "Eight of Swords": {
    en: "Eight of Swords",
    es: "Ocho de Espadas",
    de: "Acht der Schwerter",
    fr: "Huit d'Épées",
    pt: "Oito de Espadas",
    zh: "宝剑八",
    hi: "तलवारों का आठ",
    ru: "Восьмёрка Мечей",
    hy: "Սրերի Ութ"
  },
  "Nine of Swords": {
    en: "Nine of Swords",
    es: "Nueve de Espadas",
    de: "Neun der Schwerter",
    fr: "Neuf d'Épées",
    pt: "Nove de Espadas",
    zh: "宝剑九",
    hi: "तलवारों का नौ",
    ru: "Девятка Мечей",
    hy: "Սրերի Իննը"
  },
  "Ten of Swords": {
    en: "Ten of Swords",
    es: "Diez de Espadas",
    de: "Zehn der Schwerter",
    fr: "Dix d'Épées",
    pt: "Dez de Espadas",
    zh: "宝剑十",
    hi: "तलवारों का दस",
    ru: "Десятка Мечей",
    hy: "Սրերի Տասը"
  },
  "Page of Swords": {
    en: "Page of Swords",
    es: "Sota de Espadas",
    de: "Bube der Schwerter",
    fr: "Valet d'Épées",
    pt: "Pajem de Espadas",
    zh: "宝剑侍从",
    hi: "तलवारों का पेज",
    ru: "Паж Мечей",
    hy: "Սրերի Էջ"
  },
  "Knight of Swords": {
    en: "Knight of Swords",
    es: "Caballero de Espadas",
    de: "Ritter der Schwerter",
    fr: "Cavalier d'Épées",
    pt: "Cavaleiro de Espadas",
    zh: "宝剑骑士",
    hi: "तलवारों का शूरवीर",
    ru: "Рыцарь Мечей",
    hy: "Սրերի Ասպետ"
  },
  "Queen of Swords": {
    en: "Queen of Swords",
    es: "Reina de Espadas",
    de: "Königin der Schwerter",
    fr: "Reine d'Épées",
    pt: "Rainha de Espadas",
    zh: "宝剑女王",
    hi: "तलवारों की रानी",
    ru: "Королева Мечей",
    hy: "Սրերի Թագուհի"
  },
  "King of Swords": {
    en: "King of Swords",
    es: "Rey de Espadas",
    de: "König der Schwerter",
    fr: "Roi d'Épées",
    pt: "Rei de Espadas",
    zh: "宝剑国王",
    hi: "तलवारों का राजा",
    ru: "Король Мечей",
    hy: "Սրերի Թագավոր"
  },
   "Ace of Wands": {
    en: "Ace of Wands",
    es: "As de Bastos",
    de: "Ass der Stäbe",
    fr: "As de Bâtons",
    pt: "Ás de Paus",
    zh: "权杖王牌",
    hi: "छड़ी का इक्का",
    ru: "Туз Жезлов",
    hy: "Գավազանների տուզ"
  },
  "Two of Wands": {
    en: "Two of Wands",
    es: "Dos de Bastos",
    de: "Zwei der Stäbe",
    fr: "Deux de Bâtons",
    pt: "Dois de Paus",
    zh: "权杖二",
    hi: "छड़ियों का दो",
    ru: "Двойка Жезлов",
    hy: "Գավազանների երկուս"
  },
  "Three of Wands": {
    en: "Three of Wands",
    es: "Tres de Bastos",
    de: "Drei der Stäbe",
    fr: "Trois de Bâtons",
    pt: "Três de Paus",
    zh: "权杖三",
    hi: "छड़ियों का तीन",
    ru: "Тройка Жезлов",
    hy: "Գավազանների երեք"
  },
  "Four of Wands": {
    en: "Four of Wands",
    es: "Cuatro de Bastos",
    de: "Vier der Stäbe",
    fr: "Quatre de Bâtons",
    pt: "Quatro de Paus",
    zh: "权杖四",
    hi: "छड़ियों का चार",
    ru: "Четвёрка Жезлов",
    hy: "Գավազանների չորս"
  },
  "Five of Wands": {
    en: "Five of Wands",
    es: "Cinco de Bastos",
    de: "Fünf der Stäbe",
    fr: "Cinq de Bâtons",
    pt: "Cinco de Paus",
    zh: "权杖五",
    hi: "छड़ियों का पाँच",
    ru: "Пятёрка Жезлов",
    hy: "Գավազանների հինգ"
  },
  "Six of Wands": {
    en: "Six of Wands",
    es: "Seis de Bastos",
    de: "Sechs der Stäbe",
    fr: "Six de Bâtons",
    pt: "Seis de Paus",
    zh: "权杖六",
    hi: "छड़ियों का छह",
    ru: "Шестёрка Жезлов",
    hy: "Գավազանների վեց"
  },
  "Seven of Wands": {
    en: "Seven of Wands",
    es: "Siete de Bastos",
    de: "Sieben der Stäbe",
    fr: "Sept de Bâtons",
    pt: "Sete de Paus",
    zh: "权杖七",
    hi: "छड़ियों का सात",
    ru: "Семёрка Жезлов",
    hy: "Գավազանների յոթ"
  },
  "Eight of Wands": {
    en: "Eight of Wands",
    es: "Ocho de Bastos",
    de: "Acht der Stäbe",
    fr: "Huit de Bâtons",
    pt: "Oito de Paus",
    zh: "权杖八",
    hi: "छड़ियों का आठ",
    ru: "Восьмёрка Жезлов",
    hy: "Գավազանների ութ"
  },
  "Nine of Wands": {
    en: "Nine of Wands",
    es: "Nueve de Bastos",
    de: "Neun der Stäbe",
    fr: "Neuf de Bâtons",
    pt: "Nove de Paus",
    zh: "权杖九",
    hi: "छड़ियों का नौ",
    ru: "Девятка Жезлов",
    hy: "Գավազանների ինը"
  },
  "Ten of Wands": {
    en: "Ten of Wands",
    es: "Diez de Bastos",
    de: "Zehn der Stäbe",
    fr: "Dix de Bâtons",
    pt: "Dez de Paus",
    zh: "权杖十",
    hi: "छड़ियों का दस",
    ru: "Десятка Жезлов",
    hy: "Գավազանների տասը"
  },
  "Page of Wands": {
    en: "Page of Wands",
    es: "Sota de Bastos",
    de: "Bube der Stäbe",
    fr: "Valet de Bâtons",
    pt: "Pajem de Paus",
    zh: "权杖侍者",
    hi: "छड़ियों का पेज",
    ru: "Паж Жезлов",
    hy: "Գավազանների паж"
  },
  "Knight of Wands": {
    en: "Knight of Wands",
    es: "Caballero de Bastos",
    de: "Ritter der Stäbe",
    fr: "Cavalier de Bâtons",
    pt: "Cavaleiro de Paus",
    zh: "权杖骑士",
    hi: "छड़ियों का नाइट",
    ru: "Рыцарь Жезлов",
    hy: "Գավազանների ասպետ"
  },
  "Queen of Wands": {
    en: "Queen of Wands",
    es: "Reina de Bastos",
    de: "Königin der Stäbe",
    fr: "Reine de Bâtons",
    pt: "Rainha de Paus",
    zh: "权杖皇后",
    hi: "छड़ियों की रानी",
    ru: "Королева Жезлов",
    hy: "Գավազանների թագուհի"
  },
  "King of Wands": {
    en: "King of Wands",
    es: "Rey de Bastos",
    de: "König der Stäbe",
    fr: "Roi de Bâtons",
    pt: "Rei de Paus",
    zh: "权杖国王",
    hi: "छड़ियों का राजा",
    ru: "Король Жезлов",
    hy: "Գավազանների արքա"
  }
};
